### ISSUE TITLE
 ripple effect applied when button is disabled

### ISSUE THREAD

**Issue by 6gsaifulislam** [jadjoubran/angular-material-design-lite#11]
One thing that might be annoying is that if you disable a button with ng-disabled but the ripple class is applied then it will still apply the ripple effect when the button is pressed even when disabled. My solution was to change the ng-class which applied the ripple effect to include the check for the disable value.

**Comment by jadjoubran** [comment]
okay
thanks for reporting this!

Would it be possible to provide a PR?
I'm flying tomorrow so I might not be available before next week

**Comment by rohullah-ayoub** [comment]
Working on this.

**Comment by jadjoubran** [comment]
Thanks a lot @sarthair!

**Comment by rohullah-ayoub** [comment]
No problem @jadjoubran

**Comment by jadjoubran** [comment]
Closed via #25
