### ISSUE TITLE
material design ng-view issue

### ISSUE THREAD

**Issue by mrfaizanhaider** [jadjoubran/angular-material-design-lite#12]
all mdl components work wihtout ng-view but with ng-view did'nt work any component...

please help

**Comment by jadjoubran** [comment]
Hi,

If your content are being dynamically loaded then you probably need to use `mdl-upgrade` attribute:

Check the docs: [upgrading components](https://desolate-fjord-7338.herokuapp.com/#upgrading_components)

**Comment by mrfaizanhaider** [comment]
You rock man. You save my ass... thanks

**Comment by jadjoubran** [comment]
Sure :D

Feel free to open a new issue if you have other questions!
