### ISSUE TITLE
Angular mdl input type issue

### ISSUE THREAD

**Issue by mrfaizanhaider** [jadjoubran/angular-material-design-lite#13]
How to use input Types in mdl angular with validation errors????

<mdl-text-field label="Password" mdl-upgrade ng-model="password"></mdl-text-field>

**Comment by jadjoubran** [comment]
What do you mean?
Can you provide an example in MDL?

**Comment by mrfaizanhaider** [comment]
let's say this a E-mail input field...

<mdl-text-field label="email" mdl-upgrade ng-model="email"></mdl-text-field>

and in email input , just should be type email address. and if i type some numbers in email text files ,input say email invalid...

when you type some abc letters in number textfield , number textfiled show errors , 
Input is not a number!

like this... 
http://www.getmdl.io/components/index.html#textfields-section

btw it's working without angular , but it is possible in angular.

**Comment by jadjoubran** [comment]
hmm can you please provide a working codepen? So I can see it in action and develop a fix
Thanks!

**Comment by mrfaizanhaider** [comment]
Plese check this link
http://bigbeehive.com/demo/faizan/study/mdl

1st check the bottom last textfields. they are with simple html5 markup but with types.

2nd you see top textfields with angular ,here is not type.

Question.. how to add input types in mdl angular textfields..

**Comment by jadjoubran** [comment]
I think this is related to issue #9 
can you confirm?

**Comment by jadjoubran** [comment]
Feel free to re-open if the issue persists
