### ISSUE TITLE
how do i let it work in template.html when i use the ngRute

### ISSUE THREAD

**Issue by linuxwit** [jadjoubran/angular-material-design-lite#14]
when i write a template page  
and i use the ngRute

the ui is worked but the input event not working

**Comment by jadjoubran** [comment]
Hi @linuxwit 
Thanks for opening an issue.

Can you please elaborate more on the issue?

What's not working with the input event?
Can you show some sample code?

**Comment by jadjoubran** [comment]
Feel free to re-open if the issue persists
