### ISSUE TITLE
Layout Drawer question

### ISSUE THREAD

**Issue by ogranada** [jadjoubran/angular-material-design-lite#18]
Hello, great job and thanks for it. I have a questions, angular-material-design-lite suport mdl-layout__drawer? ho ca I use it?.

Thanks.

**Comment by jadjoubran** [comment]
Hi @ogranada 
AMDL doesn't have a directive for the drawers yet so you can just use the native MDL component for that - just like they have it on the MDL docs

Feel free to submit a PR for this if you want

Cheers

**Comment by ogranada** [comment]
I try make a directive to use it, but MDL library use a structure that does not work when a directive exists because MDL use a specific DOM structure, you have suggestions for make a custom directive?

**Comment by jadjoubran** [comment]
Can you provide a codepen that illustrates the issue you're having? That way I can try and fix it
