### ISSUE TITLE
Initial state of checkbox

### ISSUE THREAD

**Issue by djalmaaraujo** [jadjoubran/angular-material-design-lite#19]
I am trying to start the 
`<mdl-switch label="Notifications" ng-model="attendee.name" mdl-upgrade></mdl-switch>`

as checked, but it's not working. Is there an issue about that?

**Comment by jadjoubran** [comment]
Hi @djalmaaraujo 
Thanks for opening an issue

Please provide a codepen so we can identify the issue
Cheers
