### ISSUE TITLE
Npm support?

### ISSUE THREAD

**Issue by sebastiendan** [jadjoubran/angular-material-design-lite#27]
Hi,

Any chance of porting your module as an npm package?
I'd like to get rid of bower and use only npm for external libraries (mainly because I'm playing with Webpack which is better used with npm modules only).

Thanks!

**Comment by jadjoubran** [comment]
Hi @sebastiendan 
Yes sure! Would you be able to send a PR? Or at least point me in the right direction to make it also exportable for npm modules (never done this before)

Thanks!

**Comment by sebastiendan** [comment]
No pb, I've never done it either but will try soon.
Should be pretty straightforward from this:

https://docs.npmjs.com/getting-started/creating-node-modules

**Comment by sebastiendan** [comment]
Any news on this? I actually did my first npm module a few days ago, it really is easy and takes no more than 5 min. 

Thanks for your work!

**Comment by jadjoubran** [comment]
Oh I thought you were going to send a PR
Let me know if you can't, so I'll do it

**Comment by sebastiendan** [comment]
Actually you just have to check information in package.json is correct and then run `npm publish`. It has to be done with your npm account otherwise it won't be under your control, so there's nothing much I can do with a PR :)

**Comment by jadjoubran** [comment]
Oh that's right! I thought there something that needed to be fixed in the `package.json`
It's published now [here](https://www.npmjs.com/package/angular-material-design-lite)
Let me know if it doesn't work

**Comment by sebastiendan** [comment]
Works like a charm, thank you!
Nevertheless I have 2 suggestions:
- You should update your readme
- I don't know if this is the best practise but in `package.json` I would config `main` as minified version of your script. Anyway your script is very light so it's ok as it is now.

Thank you for prompt reply and change on this!

Cheers!

**Comment by jadjoubran** [comment]
Thanks!
Fixed in 0.4.4
Also moved express from `dependencies` to `devDependencies`
