### ISSUE TITLE
any progress soon?

### ISSUE THREAD

**Issue by antonioaltamura** [jadjoubran/angular-material-design-lite#28]
Hi, I appreciated this work, but currently the directives are 7, Any plan to extend the support soon?

**Comment by jadjoubran** [comment]
Hi @antonioaltamura, thanks!
Would you be interested in submitting a PR for some new directives?

**Comment by antonioaltamura** [comment]
I don't have so much free time, but I guess I can PR some simple directives..anyway maybe it's not worths spending a long time on it since Angular 1 is going to dismiss..

**Comment by jadjoubran** [comment]
yeah exactly 😄
