### ISSUE TITLE
Nav links not working with (responsive) drawer layout

### ISSUE THREAD

**Issue by benoror** [jadjoubran/angular-material-design-lite#3]
Fore some reason anchors won't work when using a small screen (or scaling the browser window)

```
<div class="mdl-layout__drawer">
      <span class="mdl-layout-title">Material Design Lite</span>
      <nav class="mdl-navigation">
        <a href="#overview" class="mdl-navigation__link">Overview</a>
        <a href="#types" class="mdl-navigation__link">Custom Types</a>
      </nav>
</div>
```

Tested on both:
- [jadjoubran.github.io/angular-material-design-lite](http://jadjoubran.github.io/angular-material-design-lite/)
- [angular-formly.com/#/example/integrations/angular-material-lite](http://angular-formly.com/#/example/integrations/angular-material-lite) (https://github.com/formly-js/angular-formly-website/pull/53)

**Comment by jadjoubran** [comment]
Is that an issue with MDL itself?
Can you please post a working plnkr

**Comment by benoror** [comment]
I think you're right, it might be an MDL issue ![Screenshot](http://i.imgur.com/AS3ChGJ.png)

**Comment by jadjoubran** [comment]
I originally got it from this template here: http://www.getmdl.io/templates/text-only/index.html

But apparently the drawer functionality is not there anymore.

So I just updated [gh-pages](jadjoubran.github.io/angular-material-design-lite) to make it work just like they did. But you have to enable mobile view and choose android or ios then refresh for it to work. I don't know why this is necessary for it to work.. but this is also the case on their website

The commit can help you: https://github.com/jadjoubran/angular-material-design-lite/commit/3fe75c89ce3318eee359862dd086e12095488973

Let me know if it fixes it for you :D

**Comment by benoror** [comment]
Hi Jad, thanks for the response.

Actually I don't see the drawer anymore, but I can't see the top navbar either:

![Comparison](http://i.imgur.com/Rk5X5oB.png)

**Comment by jadjoubran** [comment]
Yes, if I'm not mistaken, the same happens in the Material Design Lite template.

You need to open your Chrome dev tools and select Mobile emulation and choose a device then refresh the page.

Let me know if it works with you. And you can try it again on the demo to see if it's from the MDL library

**Comment by benoror** [comment]
It works that way, but shouldn't it be responsive when simply resizing the browser (viewport)?

Sorry for the inconvenience, I'm not a CSS expert. You can close the issue, thanks!

**Comment by jadjoubran** [comment]
No worries I'd love to help!

And usually, responsive is when you simply resize the browser/viewport. But I guess it's not the case even here right?

Give it a try. If it doesn't work, then maybe we can open a bug on MDL's main github repository:

http://www.getmdl.io/templates/text-only/index.html

**Comment by jadjoubran** [comment]
@benoror did you try it? :D

**Comment by benoror** [comment]
Sorry for the delay, I'm on holidays. Both examples worked fine on mobile
emulation. But your example didn't work when resizing the browser, as you
can see in the screenshot.

Kind regards!

On Fri, Jul 17, 2015 at 2:27 PM Jad Joubran notifications@github.com
wrote:

> @benoror https://github.com/benoror did you try it? :D
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/jadjoubran/angular-material-design-lite/issues/3#issuecomment-122384956
> .
> 
> ## 

Sent from my phone (sorry for possible typos)
Benjamin Orozco - benoror.com

**Comment by jadjoubran** [comment]
Thank you for your reply!
Yes I am aware of that. But have you tried MDL's original example when resizing the browser? Because it doesn't work for me which means it's probably a bug in MDL's library

**Comment by benoror** [comment]
As shown in the screenshot, it works for me. Am I missing something?

![Comparison](http://i.imgur.com/ApHnXBP.png)

**Comment by jadjoubran** [comment]
Oh!!! It was still not working on my end, but as soon as I hard refreshed it started working. So apparently they released a new version or a new code that fixes it!
Thank you very much for pointing it out
I'll look into it as soon as possible

**Comment by benoror** [comment]
Nope, it looks you are using the [latest version](https://github.com/google/material-design-lite/releases) (1.0.0): 
- http://jadjoubran.github.io/angular-material-design-lite/bower_components/material-design-lite/material.min.css
- https://desolate-fjord-7338.herokuapp.com/js/material.min.js

Seems more like an implementation issue imho

**Comment by jadjoubran** [comment]
Fixed! It turned out to be a z-index problem.
Thank you very much for pointing it out and sorry it took so long to be resolved.

Feel free to open a new issue anytime!
