### ISSUE TITLE
typing error in demo

### ISSUE THREAD

**Issue by 6gsaifulislam** [jadjoubran/angular-material-design-lite#5]
Hi - It's nothing major - but have a look at the label for the radio buttons the demo shows both as being set to "male"

**Comment by jadjoubran** [comment]
Great, thanks for noticing!
Working on a fix

**Comment by jadjoubran** [comment]
Updated docs, thanks again!

Feel free to open a new issue

**Comment by 6gsaifulislam** [comment]
Out of interest - have you tried the radio button within a template - with me it will accept the selected value but not show the unselected I think it has something to do with componentHandler.upgradeAllRegistered() but putting that in makes no difference.

**Comment by jadjoubran** [comment]
Can you provide a working plnkr or codepen?
Actually it would be great if you can open a new issue so that it would be helpful for other people

**Comment by 6gsaifulislam** [comment]
Will try I am using Meteor with Angular - it might take some time!

**Comment by jadjoubran** [comment]
okay

**Comment by 6gsaifulislam** [comment]
Sorry can't get the template error reproduced - I think it is because codepen is reading the template whereas I would use a separate file (don't know how to do that in codepen). 
Anyway here is the codepen http://codepen.io/anon/pen/NqeXGB it shows the issue with componentHandler.upgradeAllRegistered(). If you don't include it in the link function the buttons are not styled. The issue is that the componentHandler does not want to be in the link function as it would be called for every item used

**Comment by jadjoubran** [comment]
hmm I don't get what's the issue? When I enable componentHandler.upgradeAllRegistered() it works..

**Comment by 6gsaifulislam** [comment]
Its an issue I keep running into:
The problem is that when calling componentHandler.upgradeAllRegistered()  it will not apply to item which are hidden by ng-if.
To me three are three solutions - 1) do not use ng-if and use ng-show or ng-hide instead 2) call the code in the link function or 3) call the code in the controller whenever the value for ng-if changes to true.
I do not like option 1 as it code slow things down - ok for small projects but on a large page?
Option 2 - Using the link function could call the same code over and over again.
Option 3 - could become difficult to keep track off.

Perhaps it's just me I tend to use ng-if a lot!

**Comment by jadjoubran** [comment]
This is the issue that we're trying to solve in issue #4.. using ng-if is totally fine
I'm hoping for a fix soon
it's something that angular-material-design-lite should do out of the box..

**Comment by jadjoubran** [comment]
@JohnAReid I've got a fix for you, checkout the new documentation and issue #4 and let me know what you think.

**Comment by rr19** [comment]
@jadjoubran Hi - had a play with it with mixed results - it seems to pick up the formatting but not sure about the js code. Material lite seems to have changed over the past few days - md switch seems to work now without the upgrade code. I stopped using the check box as it would not work correctly for me.

**Comment by jadjoubran** [comment]
Can you show me a codepen with the new issue? Maybe the switches are not being dynamically injected anymore?

**Comment by rr19** [comment]
Sorry the codepen I used before often did not reproduce the errors the encountered. I know before last week I  had to use the upgrade js code otherwise they were being shown as a un-styled check box.

Generally I am very happy with MDL - but then again I only use the button, menu and tab control.
