### ISSUE TITLE
Switch not responding to model change

### ISSUE THREAD

**Issue by shellydehaven** [jadjoubran/angular-material-design-lite#8]
Frist, so happy to see this being developed - thanks.  With the progress bar, you are watching the progress and updating the control accordingly.  With the switch, this doesn't seem to be the case.  With angular material design, an update to the model causes the switch ui to refresh.  Do you have plans to provide this?

**Comment by jadjoubran** [comment]
Thank you :D

That's indeed a valid point! Would you be interested in submitting a PR? If not, I can take care of it

**Comment by jadjoubran** [comment]
I'm working on a fix

**Comment by jadjoubran** [comment]
Update your dependency to 0.4.1 to get the update
Release note: https://github.com/jadjoubran/angular-material-design-lite/releases/tag/0.4.1

**Comment by jadjoubran** [comment]
Also check this for a [demo](https://github.com/jadjoubran/angular-material-design-lite/blob/master/examples/index.html#L31)

**Comment by shellydehaven** [comment]
Thanks.  At this time, due to its size, and only needing the switch, we’ve decided to not use MDL.  I’ll be sure to check back if that changes.  Thanks again.
